algoritmo "analizador de nomes"

var

    nome: Caractere

inicio

    escreva("Digite um nome: ")
    Leia(nome)
    escreval("Total de letras no seu nome: ", compr(nome))
    escreval("Seu nome com  letras maiúsculas: " , Maiusc(nome))
    escreval("com letras minúsculas: " , Minusc(nome))
    escreval("A primeira letra do seu nome é: ", Copia(nome, 0, 1))
    escreval("A última letra do seu nome é: ", copia(nome , compr(nome) , 1))

fimalgoritmo