algoritmo "Conte de 0 até onde o usuário quiser"

var

    contador:Inteiro
    L, S:Inteiro

inicio

    escreval("Até onde você deseja contar? ")
    leia(L)
    escreval("Qual será o valor do salto? ")
    Leia(S)

        contador <- 0
        enquanto (contador <= L) faca
            escreval(contador)
            contador <- contador +S
        fimenquanto

    escreval("Terminou a contagem")

fimalgoritmo