algoritmo "Funcionário"

var

    nome: Caractere
    salario: Real
    data: Caractere

inicio

    escreval("Insira seu nome: ")
    Leia (Nome)

    escreval("Insira seu salário: ")
    leia (salario)

    escreval("Data de hoje: ")
    Leia (data)

        escreval("Nome do funcionário: " , Nome)
        escreval("Salário: R$" , salario)

        escreval("O funcionário " , Nome , " Possui um salário de R$" , salario, " em " , data)

fimalgoritmo